[book]
authors = ["subfish","toaster"]
language = "zh"
multilingual = false
src = "src"
title = "translation of Mathematics in Lean"

[output.html]
git-repository-url = "https://github.com/RedBlack23/mathematics_in_lean_zhCN"